# Generated by Django 5.0.7 on 2024-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='accounts/default.jpg', null=True, upload_to='accounts/'),
        ),
    ]
